### model
model_name_or_path: /root/autodl-tmp/Meta-Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: ChemDual
dataset: compound_train,smiles_train
template: llama3
cutoff_len: 1024
max_samples: 3000000
overwrite_cache: true
preprocessing_num_workers: 48

### output
output_dir: saves/ChemDual/train_2024-08-09
logging_steps: 10
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
bf16: true
ddp_timeout: 180000000
include_num_input_tokens_seen: True

### eval
val_size: 0.0005
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 2000
